---
- hosts: k8s-master
  gather_facts: false
  become: yes
  tasks:
    - name: k8s-worker | create join command
      shell: kubeadm token create --print-join-command
      register: join

    - name: k8s-worker | set join command
      set_fact:
        join_command: "{{ join.stdout_lines[0] }}"

- hosts: k8s-worker
  become: yes
  tasks:
    - name: k8s-worker | join cluster
      shell: "{{ hostvars['master'][0].join_command }}"