---
- hosts: k8s-all
  gather_facts: false
  become: yes
  tasks:
    - name: common | create ubuntu sudoers file
      lineinfile:
        dest: "/etc/sudoers.d/{{ linux.user }}"
        line: "{{ linux.user }} ALL=(ALL) NOPASSWD:ALL"
        validate: /usr/sbin/visudo -cf %s

    - name: common | disable swap
      lineinfile:
        path: /etc/fstab
        regexp: 'swap'
        state: absent

    - name: common | network settings specific for k8s
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        block: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1

    - name: common | memory settings specific for elasticsearch
      blockinfile:
        path: /etc/sysctl.conf
        block: |
          sysctl -w vm.max_map_count=262144

    - name: common | install common packages
      apt:
        force_apt_get: yes
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - net-tools
        state: latest

    - name: common | add docker apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: common | add docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        state: present
        filename: docker-ce

    - name: common | install docker
      apt:
        force_apt_get: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes
    
    - name: "common | add docker group to {{ linux.user }}"
      user:
        name: "{{ linux.user }}"
        groups: docker
        append: yes

    - name: common | enable docker service
      service:
        name: docker
        enabled: yes

    - name: common | add kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: common | add kubernetes repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes

    - name: common | install kubernetes
      apt:
        force_apt_get: yes
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        update_cache: yes

    - name: common | prevent kubernetes being updated unless planned
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: common | reboot
      reboot:
